"""Tests for voice_mode/silero_vad.py (SileroVAD + Endpointer).

Two complementary layers, per the dispatch that built this module:

  - "Scripted" tests feed Endpointer a hand-authored SEQUENCE of P(speech)
    values via a stand-in for SileroVAD, bypassing the real model entirely.
    This tests the Endpointer STATE MACHINE's timing logic deterministically
    and independent of what any particular audio scores -- the foundation
    layer for D1 (fires within ~min_endpoint_ms of speech ending), D2 (a
    high-ENERGY but low-PROB trailing segment doesn't delay/prevent
    endpointing), and D3 (continuous low-level background prob still lets
    endpointing fire).
  - "Real-onnx" tests exercise the actual vendored model -- a bare smoke
    test, plus end-to-end tests against the committed fixtures in
    tests/fixtures/endpointing/ (generated by generate_fixtures.py), which
    is the strongest evidence: real audio, real model, real timing.

Skipped (not failed) wherever SILERO_AVAILABLE is False, so this suite is
still meaningful in a webrtcvad-only environment (onnxruntime not
installed) -- the scripted Endpointer-timing tests do NOT need the real
model at all and always run.
"""

from pathlib import Path

import numpy as np
import pytest
from scipy import signal as sp
from scipy.io import wavfile

from voice_mode import silero_vad
from voice_mode.silero_vad import Endpointer, EndpointState, SileroVAD, SILERO_AVAILABLE

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "endpointing"
VAD_SR = 16000
FRAME_MS = 30
FRAME_SAMPLES = int(VAD_SR * FRAME_MS / 1000)  # 480, matches this codebase's VAD chunking


# --------------------------------------------------------------------------
# Scripted P(speech) stand-in -- see module docstring. Ignores the actual
# audio content of each frame entirely; only its LENGTH matters (drives the
# Endpointer's ms accounting via _frame_duration_ms).
# --------------------------------------------------------------------------
class _ScriptedVAD:
    def __init__(self, probs):
        self._probs = list(probs)
        self._i = 0

    def prob(self, frame) -> float:
        p = self._probs[min(self._i, len(self._probs) - 1)]
        self._i += 1
        return p

    def reset(self) -> None:
        self._i = 0


def _make_endpointer(probs, **kwargs) -> Endpointer:
    """An Endpointer wired to a _ScriptedVAD instead of the real SileroVAD --
    construction still goes through the real Endpointer.__init__ (so ctor
    args/validation are exercised), only the inner detector is swapped."""
    ep = Endpointer(**kwargs)
    ep._vad = _ScriptedVAD(probs)
    return ep


def _frame(n: int = FRAME_SAMPLES) -> np.ndarray:
    """A frame whose CONTENT is irrelevant to _ScriptedVAD but whose length
    drives ms accounting; int16 zeros keep it cheap and obviously not the
    thing driving the probability."""
    return np.zeros(n, dtype=np.int16)


def _loud_frame(n: int = FRAME_SAMPLES, seed: int = 0) -> np.ndarray:
    """A frame with real, high int16 energy -- used in the D2 test to prove
    the Endpointer's decision tracks the SCRIPTED PROBABILITY, not this
    frame's actual loudness."""
    rng = np.random.default_rng(seed)
    return (rng.standard_normal(n) * 12000).astype(np.int16)


class TestEndpointerTimingScripted:
    """D1/D2/D3 foundation: Endpointer's state-machine timing, independent
    of the real model."""

    def test_d1_endpoints_within_min_endpoint_ms_of_speech_ending(self):
        min_speech_ms = 200
        min_endpoint_ms = 700
        speech_frames = -(-min_speech_ms // FRAME_MS)  # ceil
        silence_frames_needed = -(-min_endpoint_ms // FRAME_MS)  # ceil

        probs = [0.9] * speech_frames + [0.05] * (silence_frames_needed + 3)
        ep = _make_endpointer(
            probs, sample_rate=VAD_SR, speech_threshold=0.5,
            min_endpoint_ms=min_endpoint_ms, min_speech_ms=min_speech_ms,
        )

        states = [ep.update(_frame()) for _ in probs]

        # speech_started must flip True once min_speech_ms of above-threshold
        # frames have accumulated, and NOT before.
        first_speech_started = next(i for i, s in enumerate(states) if s.speech_started)
        assert first_speech_started == speech_frames - 1

        # endpointed must flip True within one frame of min_endpoint_ms of
        # CONSECUTIVE sub-threshold time after speech started -- not late by
        # more than a frame, not early.
        first_endpointed = next(i for i, s in enumerate(states) if s.endpointed)
        below_threshold_frames_at_endpoint = first_endpointed - (speech_frames - 1)
        elapsed_ms = below_threshold_frames_at_endpoint * FRAME_MS
        assert elapsed_ms >= min_endpoint_ms
        assert elapsed_ms < min_endpoint_ms + FRAME_MS, (
            f"endpointed fired {elapsed_ms}ms after speech ended, expected within "
            f"one frame of {min_endpoint_ms}ms"
        )
        # And nothing before speech even started should ever endpoint.
        assert not any(s.endpointed for s in states[:speech_frames])

    def test_d2_high_energy_low_prob_tail_does_not_delay_or_prevent_endpointing(self):
        """The core bug this whole workstream fixes: webrtcvad's binary
        decision lets steady ENERGY (breath/noise) hold a turn open. Prove
        the Endpointer does NOT do that -- feed genuinely loud int16 frames
        (real energy) whose SCRIPTED probability is low, and confirm
        endpointing proceeds on the normal min_endpoint_ms schedule, not
        delayed or blocked by the frames' actual loudness."""
        min_speech_ms = 200
        min_endpoint_ms = 700
        speech_frames = -(-min_speech_ms // FRAME_MS)
        tail_frames = -(-min_endpoint_ms // FRAME_MS) + 3

        probs = [0.9] * speech_frames + [0.05] * tail_frames
        ep = _make_endpointer(
            probs, sample_rate=VAD_SR, speech_threshold=0.5,
            min_endpoint_ms=min_endpoint_ms, min_speech_ms=min_speech_ms,
        )

        loud_tail_frames = [_loud_frame(seed=i) for i in range(tail_frames)]
        # Sanity: these ARE loud (a plain energy gate would call them speech).
        for f in loud_tail_frames:
            assert np.sqrt(np.mean(f.astype(np.float64) ** 2)) > 5000

        states = [ep.update(_frame()) for _ in range(speech_frames)]
        states += [ep.update(f) for f in loud_tail_frames]

        first_endpointed = next(i for i, s in enumerate(states) if s.endpointed)
        below_threshold_frames_at_endpoint = first_endpointed - (speech_frames - 1)
        elapsed_ms = below_threshold_frames_at_endpoint * FRAME_MS
        assert min_endpoint_ms <= elapsed_ms < min_endpoint_ms + FRAME_MS, (
            "a loud but low-probability tail should endpoint on the same schedule "
            "as a quiet one -- energy must not delay/prevent it"
        )

    def test_d3_continuous_low_level_background_prob_still_endpoints(self):
        """Continuous, non-zero-but-sub-threshold probability (what a
        real quieter background babble bed scores, per
        generate_fixtures.py's calibration) must still let endpointing
        fire -- it's not just a TRUE-ZERO/silence case that works."""
        min_speech_ms = 200
        min_endpoint_ms = 700
        speech_frames = -(-min_speech_ms // FRAME_MS)
        tail_frames = -(-min_endpoint_ms // FRAME_MS) + 3

        rng = np.random.default_rng(5)
        # Fluctuating but always < speech_threshold=0.5 -- like a continuous
        # background bed's prob trace (see generate_fixtures.py calibration:
        # background-only tail mean_prob=0.0108 max=0.0405, never near 0.5).
        low_probs = list(np.clip(0.15 + 0.1 * rng.standard_normal(tail_frames), 0.0, 0.45))
        probs = [0.9] * speech_frames + low_probs
        ep = _make_endpointer(
            probs, sample_rate=VAD_SR, speech_threshold=0.5,
            min_endpoint_ms=min_endpoint_ms, min_speech_ms=min_speech_ms,
        )

        states = [ep.update(_frame()) for _ in probs]
        assert any(s.endpointed for s in states), (
            "a continuously sub-threshold (but nonzero) probability trace must "
            "still accumulate to an endpoint"
        )

    def test_resumed_speech_resets_the_trailing_silence_counter(self):
        """A probability blip back above threshold mid-trailing-silence
        cancels the countdown in progress (mirrors converse.py's existing
        SILENCE_AFTER_SPEECH state machine) -- endpointing should NOT fire
        at the originally-scheduled time."""
        min_speech_ms = 200
        min_endpoint_ms = 700
        speech_frames = -(-min_speech_ms // FRAME_MS)
        almost_endpoint_frames = -(-min_endpoint_ms // FRAME_MS) - 1  # one short of firing

        probs = (
            [0.9] * speech_frames
            + [0.05] * almost_endpoint_frames
            + [0.9] * speech_frames  # resumes speech, resets the below-counter
            + [0.05] * (almost_endpoint_frames + 5)
        )
        ep = _make_endpointer(
            probs, sample_rate=VAD_SR, speech_threshold=0.5,
            min_endpoint_ms=min_endpoint_ms, min_speech_ms=min_speech_ms,
        )
        states = [ep.update(_frame()) for _ in probs]

        # Must NOT have endpointed during the first near-miss window.
        first_block_end = speech_frames + almost_endpoint_frames
        assert not any(s.endpointed for s in states[:first_block_end])
        # But must eventually endpoint once the SECOND trailing-silence run
        # actually reaches min_endpoint_ms.
        assert states[-1].endpointed

    def test_endpointed_latches_true(self):
        """Once fired, endpointed stays True even if probability rises again
        afterward -- callers reset() for a fresh turn rather than relying on
        an un-endpoint transition."""
        probs = [0.9, 0.9] + [0.05] * 30 + [0.9] * 5
        ep = _make_endpointer(
            probs, sample_rate=VAD_SR, speech_threshold=0.5,
            min_endpoint_ms=700, min_speech_ms=60,
        )
        states = [ep.update(_frame()) for _ in probs]
        first_endpointed = next(i for i, s in enumerate(states) if s.endpointed)
        assert all(s.endpointed for s in states[first_endpointed:])

    def test_reset_clears_all_state(self):
        probs = [0.9] * 10 + [0.05] * 30
        ep = _make_endpointer(
            probs, sample_rate=VAD_SR, speech_threshold=0.5,
            min_endpoint_ms=700, min_speech_ms=60,
        )
        for _ in probs:
            ep.update(_frame())
        assert ep._endpointed  # sanity: it did fire

        ep.reset()
        ep._vad = _ScriptedVAD([0.05] * 5)  # reset() clears _vad state too; re-attach the stub
        state = ep.update(_frame())
        assert state == EndpointState(speech_started=False, endpointed=False, speech_prob=0.05)


class TestSileroDegradesGracefully:
    def test_silero_unavailable_construction_never_raises(self, monkeypatch):
        monkeypatch.setattr(silero_vad, "_SHARED_SESSION", None)
        monkeypatch.setattr(silero_vad, "SILERO_AVAILABLE", False)
        # Construction must succeed even with onnxruntime/model unavailable --
        # only prob() raises, per the frozen interface.
        vad = SileroVAD(sample_rate=16000)
        assert vad._session is None
        ep = Endpointer(sample_rate=16000)
        assert ep is not None

    def test_silero_unavailable_prob_raises_clear_runtime_error(self, monkeypatch):
        monkeypatch.setattr(silero_vad, "_SHARED_SESSION", None)
        monkeypatch.setattr(silero_vad, "SILERO_AVAILABLE", False)
        vad = SileroVAD(sample_rate=16000)
        with pytest.raises(RuntimeError, match="unavailable"):
            vad.prob(np.zeros(FRAME_SAMPLES, dtype=np.int16))

    def test_silero_unavailable_endpointer_update_raises(self, monkeypatch):
        monkeypatch.setattr(silero_vad, "_SHARED_SESSION", None)
        monkeypatch.setattr(silero_vad, "SILERO_AVAILABLE", False)
        ep = Endpointer(sample_rate=16000)
        with pytest.raises(RuntimeError, match="unavailable"):
            ep.update(np.zeros(FRAME_SAMPLES, dtype=np.int16))

    def test_module_imports_cleanly_without_onnxruntime(self, monkeypatch):
        """Simulates the ImportError path directly -- re-running the
        import-time availability computation with onnxruntime "absent"
        must not raise."""
        monkeypatch.setattr(silero_vad, "_ONNXRUNTIME_IMPORTABLE", False)
        session = silero_vad._load_session()
        assert session is None


@pytest.mark.skipif(not SILERO_AVAILABLE, reason="onnxruntime/vendored model unavailable")
class TestSileroRealOnnxSmoke:
    def test_model_loads_and_runs_one_frame(self):
        vad = SileroVAD(sample_rate=16000)
        rng = np.random.default_rng(0)
        frame = (rng.standard_normal(FRAME_SAMPLES) * 500).astype(np.int16)
        p = vad.prob(frame)
        assert isinstance(p, float)
        assert 0.0 <= p <= 1.0

    def test_prob_is_deterministic_for_a_fresh_instance(self):
        rng = np.random.default_rng(0)
        frame = (rng.standard_normal(FRAME_SAMPLES) * 500).astype(np.int16)
        p1 = SileroVAD(sample_rate=16000).prob(frame)
        p2 = SileroVAD(sample_rate=16000).prob(frame)
        assert p1 == p2

    def test_reset_returns_to_fresh_state(self):
        vad = SileroVAD(sample_rate=16000)
        rng = np.random.default_rng(0)
        frame = (rng.standard_normal(FRAME_SAMPLES) * 500).astype(np.int16)
        p_before_any_history = vad.prob(frame)
        # Feed a bunch of loud, different frames to accumulate state...
        for i in range(10):
            vad.prob((rng.standard_normal(FRAME_SAMPLES) * 8000).astype(np.int16))
        vad.reset()
        p_after_reset = vad.prob(frame)
        assert p_before_any_history == p_after_reset

    def test_context_prefix_is_required_for_correct_probabilities(self):
        """Regression test for the root-cause bug found while building this
        module: feeding raw window_samples with NO context prefix silently
        produces near-zero probabilities for genuine speech (max ~0.069 on
        real say-synthesized speech, measured during this build). This test
        pins the FIXED behavior via SileroVAD's public prob() -- if a future
        edit reintroduces the no-context bug, this fails loudly instead of
        silently degrading detection."""
        speech_path = FIXTURES_DIR / "clean_speech_then_pause.wav"
        if not speech_path.exists():
            pytest.skip("fixtures not generated -- run generate_fixtures.py")
        sr, data = wavfile.read(speech_path)
        speech_only = data[: int(1.0 * sr)]  # first 1s is definitely speech
        x16 = _resample(speech_only, sr, VAD_SR)

        vad = SileroVAD(sample_rate=VAD_SR)
        probs = []
        for i in range(0, len(x16) - FRAME_SAMPLES, FRAME_SAMPLES):
            probs.append(vad.prob(x16[i : i + FRAME_SAMPLES]))
        assert np.mean(probs) > 0.5, (
            f"real speech scored mean P(speech)={np.mean(probs):.4f} -- if this is "
            f"anywhere near 0 (~0.001-0.07), the context-prefix fix has regressed"
        )


def _resample(x: np.ndarray, sr_in: int, sr_out: int) -> np.ndarray:
    n_out = int(len(x) * sr_out / sr_in)
    return sp.resample(x.astype(np.float64), n_out).astype(np.float32) / 32768.0


def _fixture_frames(name: str, frame_ms: int = FRAME_MS):
    sr, data = wavfile.read(FIXTURES_DIR / name)
    x16 = _resample(data, sr, VAD_SR)
    frame_n = int(VAD_SR * frame_ms / 1000)
    for i in range(0, len(x16) - frame_n, frame_n):
        yield x16[i : i + frame_n]


@pytest.mark.skipif(not SILERO_AVAILABLE, reason="onnxruntime/vendored model unavailable")
class TestEndpointerAgainstRealFixtures:
    """End-to-end: real committed audio -> real Silero model -> Endpointer.
    Requires tests/fixtures/endpointing/*.wav (committed; regenerate via
    generate_fixtures.py if scenarios change)."""

    def _run(self, fixture_name: str, **endpointer_kwargs):
        if not (FIXTURES_DIR / fixture_name).exists():
            pytest.skip(f"{fixture_name} not generated -- run generate_fixtures.py")
        ep = Endpointer(sample_rate=VAD_SR, **endpointer_kwargs)
        states = [ep.update(f) for f in _fixture_frames(fixture_name)]
        return states

    def test_d1_clean_speech_then_pause_endpoints_after_speech(self):
        states = self._run("clean_speech_then_pause.wav")
        assert any(s.speech_started for s in states), "speech segment should be detected"
        assert any(s.endpointed for s in states), "the trailing true silence must endpoint"
        first_started = next(i for i, s in enumerate(states) if s.speech_started)
        first_endpointed = next(i for i, s in enumerate(states) if s.endpointed)
        assert first_endpointed > first_started

    def test_d2_breath_tail_does_not_prevent_endpointing(self):
        """The breath tail has REAL energy (see generate_fixtures.py
        calibration: rms >= speech rms) but a low Silero probability --
        endpointing must still fire, on the audio Silero actually scored,
        not a scripted stand-in."""
        states = self._run("speech_then_breath_tail.wav")
        assert any(s.endpointed for s in states), (
            "a high-energy but low-probability breath tail must not block endpointing"
        )

    def test_d3_background_chatter_endpoints_after_foreground_stops(self):
        states = self._run("speech_with_background_chatter.wav")
        assert any(s.speech_started for s in states)
        assert any(s.endpointed for s in states), (
            "endpointing must fire once the foreground stops, even though a "
            "continuous quieter background bed keeps playing"
        )


class TestMinEndpointMsDefaultIs500(object):
    """vm-local-turntaking (2026-09-15): min_endpoint_ms's default was
    lowered 700ms -> 500ms to match OpenAI Realtime API's own server-VAD
    silence_duration_ms default (see config.py's ENDPOINTING_MIN_ENDPOINT_MS
    comment for the citation) -- the concrete "shave 200ms of dead air off
    every turn" fix. This class pins BOTH places that number is allowed to
    live (Endpointer's own ctor default, and config.py's env-var default) so
    a future edit to just one of them -- the exact drift the "Defaults match
    Endpointer's own ctor defaults" comment warns against -- fails loudly
    instead of silently diverging, and proves the state machine actually
    fires ~500ms (not ~700ms) after speech ends at that default.
    """

    def test_endpointer_ctor_default_is_500ms(self):
        ep = Endpointer()
        assert ep.min_endpoint_ms == 500

    def test_config_default_is_500ms_when_env_var_unset(self):
        import importlib
        import os as _os

        assert "VOICEMODE_MIN_ENDPOINT_MS" not in _os.environ, (
            "test env must not already override VOICEMODE_MIN_ENDPOINT_MS, "
            "or this test can't observe the true default"
        )
        from voice_mode import config as config_module

        importlib.reload(config_module)
        try:
            assert config_module.ENDPOINTING_MIN_ENDPOINT_MS == 500
        finally:
            # Leave the module as every other test in this process expects it.
            importlib.reload(config_module)

    def test_scripted_endpoint_fires_within_one_frame_of_500ms(self):
        """Same D1 shape as test_d1_endpoints_within_min_endpoint_ms_of_speech_ending
        above, pinned to the new 500ms default specifically -- proves the
        turn-taking win is real (~200ms faster than the old 700ms) and not
        just a documentation change."""
        min_speech_ms = 200
        min_endpoint_ms = 500  # the new default -- see module docstring above
        speech_frames = -(-min_speech_ms // FRAME_MS)
        silence_frames_needed = -(-min_endpoint_ms // FRAME_MS)

        probs = [0.9] * speech_frames + [0.05] * (silence_frames_needed + 3)
        ep = _make_endpointer(
            probs, sample_rate=VAD_SR, speech_threshold=0.5,
            min_endpoint_ms=min_endpoint_ms, min_speech_ms=min_speech_ms,
        )

        states = [ep.update(_frame()) for _ in probs]

        first_endpointed = next(i for i, s in enumerate(states) if s.endpointed)
        below_threshold_frames_at_endpoint = first_endpointed - (speech_frames - 1)
        elapsed_ms = below_threshold_frames_at_endpoint * FRAME_MS
        assert elapsed_ms >= min_endpoint_ms
        assert elapsed_ms < min_endpoint_ms + FRAME_MS
        # And it must be strictly faster than the old 700ms threshold would
        # have been -- the actual user-facing improvement this change buys.
        assert elapsed_ms < 700
